import React from 'react'
import Header from './Header'

const PrivacyPolicy = () => {
  return (
    <>
    <Header/>
    <div style={{width:"100%",backgroundColor:"#00A2FF",padding:"50px"}}>
    <div style={{width:"70%",marginLeft:"100px",background:"white", padding:"100px 89px"}}>
        <h3 style={{color:"#12A9FF"}}>Privacy Policy</h3>
        <h4>Updated: 28 December 2021</h4>
        <p>1 Introduction</p>
        <p> 1.1 This Privacy Policy (hereinafter: “Policy”) is used by
        “LetsFind.Live” trading under the name Universal Media
        Group LLC, a company with limited liability under the laws
        of the WY, USA, (hereinafter: “LetsFind.Live” or “we”)).
        LetsFind.Live can be reached via info@Visymosearch.net. </p> 
        <p>1.2 LetsFind.Live is committed to protecting your privacy.
        This Policy describes what we do with your data and
        applies to all information that identifies you or may be
        used to identify you with (“Personal data”) by
        LetsFind.Live, such as but not limited to processing via the
        LetsFind.Live websites (hereinafter: “Websites”). The
        Websites are intended for general audiences over the age
        of 16 years old. We do not knowingly collect information
        from children under the age of 16 years old.</p>
        <p> 1.3 If you are not at least 13 years old in the United States
        or 16 years old, please do not use the Websites.
        1.4 This Privacy Policy is provided in English. Translations
        to certain other languages may be available and can be
        requested by contacting us at info@Visymosearch.net.</p>
       
       <p>
       <p>1.5 For ease of reference, each section of this privacy
        policy is set out below:</p>
       
       <p> Introduction</p>
       <p> Processing of Personal data</p>
       <p> Purposes of the processing</p>
       <p> Legal basis of the processing</p>
       <p> Recipients of your Personal data</p>
       <p> Retention of your Personal data</p>
       <p> Safeguarding your Personal data</p>
       <p> Your rights</p> 
       <p> Amendments and questions</p>
       </p>
        
        <p>
        2 Processing of Personal data
        2.1 LetsFind.Live is a data controller under the General
        Data Protection Regulation (GDPR). This means that with
        regard to any Personal data referred to in this Policy,
        LetsFind.Live determines the purpose for which we
        process this data, and we determine the means necessary
        for the processing of this data. As a data controller, we
        process the data set out in this section. LetsFind.Live
        does not engage in automated decision-making.
        Data collected directly from you
        </p>
       <p>
        2.2 When you access our websites, we may
        (automatically) collect the following information about you
        and/or your device:
        <p> Your anonymous IP address.</p>
        <p> Your (mobile) device identifier.</p>
        <p> Information about your settings, such as screen ratio, screen resolution,
        language settings, browser information (user agent) and/or operating system.</p>
        <p> Query-string.</p>
        <p> Your website preferences.</p>
        <p> Your location and time zone.</p>
       </p>
        <p>
        2.3 If you do not provide us with the data, we are not able
        to provide you with our services.
        Data you may provide to us
        </p>
        <p>
        2.4 Access to the Websites, their content and any web
        search results generated by using the Websites in general
        do not require you to submit Personal data to us other
        than the information listed above. Under certain
        circumstances, you may wish to provide us with more
        information about yourself, for example in relation to any

        enquiry you may want to make with us or in case you apply
        for a job with us. When you are reaching out to us, we may
        process the following information about you:
        <p> Your name.</p>
        <p> Your company name.</p>
        <p> Your email address.</p>
        <p> Your website.</p>
        <p> Your professional or employment information and educational records.</p>
        <p> Any other Personal data you provide us with.</p>
        </p>
        <p>
        2.5 If you choose to provide us with any additional
        Personal data, we recommend that you limit the provision
        of such data to the absolute minimum, and we discourage
        you from providing us with any sensitive Personal data,
        such as data revealing racial or ethnic origin, political
        opinions, religious or philosophical beliefs, trade union
        membership, genetic or biometric data or data about your
        sex life or sexual orientation.
        </p>
        <p>
        Data collected via our partners
        <p>
        2.6 Third parties may be able to process data related to
        you through our websites to provide us with certain
        products and services. Such third parties may use
        technologies such as cookies, ad tags or ad beacons to
        collect information about your interaction with any
        products and services (such as advertisements) they offer
        through the Website.
        </p>
        </p>
        <p>
        2.7 To deliver relevant search results to you, we may use
        third party services, such as YouTube for video results. If
        you watch a video sourced from YouTube embedded in
        our search results page, then your use of the YouTube
        service is subject to the YouTube Terms of Service and
        the Google Privacy Policy.
        </p>
        <p>
        2.8 Third-parties who provide us with products and
            services may also place cookies, ad tags and/or beacons
            that collect the information outlined above in order to
            provide us with products and services including analytics
            tools (e.g., Google Analytics) allowing us to analyze the
            performance of our Services and advertisers and ad
            networks allowing the delivery of relevant ads. These third
            parties may also collect information about you from other
            sources and combine it with other information collected
            about you from third party websites not affiliated with us.
            For example, advertiser and advertising networks, as well
            as data analytics companies who service them, may
            participate in interest-based advertising, and track your
            activity across various sites and/or devices where they
            display ads and record your activities, so they can show
            ads that they consider relevant to you. Where necessary,
            we will obtain your consent for these activities.
        </p>
        
        <p>
            
        3 Purposes of the processing
        <p>
        3.1 Primary purposes for which we process your Personal
        data are to offer you the best services possible, to
        optimize our websites and services and to ensure
        continuity thereof. More specifically, your Personal data
        can be used for the following purposes:
        </p>
        <p>  To provide our services: we may need certain information about you to be able
        to provide our services.</p>
        <p> To customize our services: you have the option to customize the Website
        experience to your needs. To be able to remember your customizations, we
        may process Personal data about you, such as a unique ID and your
        anonymous IP address.</p>
        <p> To improve our services: our websites and services are constantly evolving,
        and we are constantly working on improving your user experience and adding
        new functionality to our websites.</p>
        <p> To secure our services: to be able to provide you with the best user experience
        possible, it is necessary to keep out hackers, automated bots or other threats.
        We are therefore constantly monitoring our services and the use of our
        services.</p>
        <p>  To communicate with you: when you contact us, we process your contact
        details such as your name and email address and any other Personal data you
        may provide to us to be able adequately revert to you on your enquiry.</p>
        <p> For marketing purposes: data on your visit to our websites may be used by our
        advertisement partners to serve you with advertisements about our services
        elsewhere.</p>
        <p> To exercise and safeguard our rights: we may need to exercise our legal rights
        in case you infringe our intellectual property, engage in fraudulent acts or act in
        violation of this Policy or our terms of service.</p>
        <p>  To compensate our partners: as we show and run advertisements, certain
        Personal data may be needed to calculate the compensation to be paid to or
        received by or from our partners.</p>
        <p> To comply with a legal obligation: we may be required by law or by a court
        order to process (and/or transfer) certain Personal data.</p>
        </p>
        <p>
        4 Legal bases of the processing
        <p>4.1 We process your Personal data on the following legal
        basis:</p>
        
        <p> Execution of a contract with you: most processing activities are carried out to
        provide you with our services. We provide our services based on our terms of
        service; a contract entered with you when using our services.</p>
        <p> Compliance with a legal obligation: we may under certain circumstances be
        legally required to process your Personal data.</p>
        <p> Our legitimate interests: your Personal data may be processed by us based on
        our legitimate interest, such as our commercial interests. This may be the case
        with, among others, (re)marketing and compensation of our partners.</p>
        <p> Your consent: should certainly processing activities are not related to our
        contract with you, a legal obligation, or our legitimate interest, then we may
        process your Personal data based on your consent.</p>
        </p>
        <p>

        </p>
       <h4>5 Recipients of your Personal data</h4>
        <p>
            5.1 LetsFind.Live may transfer your Personal data to the
            following categories of recipients:
            <p> Suppliers: when such is necessary to enable the use websites and services, we
            may transfer your Personal data to suppliers, subcontractors, and business
            partners, such as our hosting provider that hosts the Websites, the provider of
            our job application platform, partners that help us to improve the user-
            experience of our services and providers of IT support, data backup, recovery
            service and office software.</p>
            <p> Group companies: we may provide Personal data to other companies within
            the LetsFind.Live group of companies, if this is necessary for compliance,
            internal reporting, auditing, or security purposes.</p>
            <p> Professional service providers: Our accountant, legal advisers and other
            professional service providers engaged by us for compliance reasons.</p>
            <p> Advertisement partners: Information on your Website visit may be provided to
            advertisement partners to serve you with (relevant) advertisements on our
            websites and elsewhere, and to measure effectiveness of advertisements.</p>
            <p>  Marketing partners: we may provide Personal data to third parties that help us
            to market our services, to create, deliver and measure brand experience and to
            help us make better strategic decisions.</p>
            <p> Law enforcement agencies: we may be under an obligation to provide your
            information to law enforcement, regulators, courts, or other public authorities
            in relation to an official (court) order. In addition, we may provide your data to
            law enforcement agencies, regulators, courts or otherwise to exercise our
            rights.</p>
            <p>  Fraud prevention: we may engage third parties when we believe disclosure is
            necessary to investigate, prevent, or respond to suspected illegal or fraudulent
            activity or to protect the safety, rights, or property of us, our users, or others.</p>
            <p>  Third parties: we may transfer data to third parties acquiring or merging with
            LetsFind.Live, or purchasing part or all our assets, or in case of a corporate
            restructuring.</p>   
        </p>
        
        <p>
        5.2 The third parties receiving or accessing your Personal
            data might be located outside the European Economic
            Area (EEA). When transferring data for which we are
            responsible to countries outside of the EEA (so-called

            ‘third countries’), we ensure ‘appropriate safeguards. More
            specifically, we contractually bind recipients of Personal
            data to protect your data using the Standard Contractual
            Clauses (SCC’s) as approved by the European
            Commission. We will assess in advance (where necessary,
            with the help of the recipients in third countries) on a case-
            by-case basis if the law or practice of the third country
            diminishes the effectiveness of the SCC’s. In those cases,
            we will implement supplementary measures that fill the
            gaps in the protection and bring it up to the level required
            by EU law.
            6 Retention of your Personal data
            <p>6.1 We retain your Personal data for as long as necessary
            to fulfil the associated purpose as set out above. After
            that, we may retain your Personal data if this is required or
            necessary to comply with applicable law or to be able
            satisfy any legal, reporting or audit requirements. Where
            possible we anonymize or pseudo-anonymize your
            Personal data or retain it in an aggregated form only.
            7 Securing your Personal data
            7.1 We highly value the secure processing of your
            Personal data. Therefore, we may implement security
            measures, such as but not limited to, as appropriate:</p>
            
        </p>
       <p> The pseudonymization and encryption of Personal Data.</p>
       <p> The ability to ensure the ongoing confidentiality, integrity, availability and
        resilience of processing systems and services.</p>
       <p> The ability to restore the availability and access to Personal Data in a timely
        manner in the event of a physical or technical incident; and</p>
       <p> A process for regularly testing, assessing, and evaluating the effectiveness of
        technical and organizational measures for ensuring the security of the
        processing.</p>

        <p> 8 Your rights
        8.1 You are provided with the following rights:</p>    
       <p>  Objection: Under certain conditions you have the right to object to the
        processing of your Personal data and the conditions under which this
        processing takes place.</p>
       <p> Access: You have the right to request from us, without constraint, at
        reasonable intervals and without excessive delay or expense, i) a confirmation
        as to whether or not Personal data regarding you is being
        processed, ii) information on the purposes for which Personal data is
        processed, iii) the categories of Personal data concerned, and iv) the recipients
        or categories of recipients to whom the Personal data is disclosed. You have
        the right to receive, in an intelligible form, a communication of the personal
        data being processed and of any available information as to the source(s).
        Furthermore, you have the right to knowledge of the underlying logic of the
        automated processing of Personal data relating to you.</p>
       <p>  Rectification, restriction, erasure, blocking or deletion: Under certain
        conditions you have the right to rectification, restriction, erasure, blocking or
        deletion of your Personal data that is not processed in compliance with data
        protection laws and regulations, when the nature of the data is incomplete or
        inaccurate.</p>
       <p>  Data portability: Under certain conditions you have the right to receive your
        Personal data in a structured, commonly used, and machine-readable format
        to transfer those data.</p>
       <p> Withdraw consent: where we are processing Personal data relating to you
        because of your prior consent to that processing, you may withdraw your
        consent at any time.</p>
       <p> Complaint with relevant authority. You have the right to file a complaint with
        the relevant data protection authorities.</p>

<p>8.2 You may exercise these rights by contacting us via
        info@Visymosearch.net.</p>
<p>8.3 In order to fulfil your possible requests pursuant to the
        rights as stated above, we may request specific additional
        information from you to identify you with or we may ask
        you for information to identify you with. We only collect

        and process such specific data with the purpose of
        executing your above stated rights insofar this is
        requested by you.</p>
<p> 9 Amendments and questions
        9.1 LetsFind.Live may amend this Policy at any time. In
        case the Policy is amended, the amended Policy will be
        made available to you through publication of the amended
        Policy on the Website.</p>
<p>9.2 Should you have any questions after reading this
        Policy or would want to exercise any right as stated in this
        Policy, please do not hesitate to contact us via
        info@Visymosearch.net.</p>
        
        
       
        

    </div>
    </div>
     
    </>
   
  )
}

export default PrivacyPolicy